### PR TITLE
Remove debug print_r

### PR DESCRIPTION
**Pull request by ajitbohra**
debug cleanup

### CODE REVIEW

**Review by djmetzle — APPROVED** [review]
CR :beetle:

**Comment by cdcline** [comment]
CR 👍

**Comment by batbattur** [comment]
Confirmed that the debug info is removed 👍 

Tested together with https://github.com/iFixit/valkyrie/pull/508#issuecomment-875040947

Screen Shot 2021-07-06 at 12 46 02 PM


QA 👍

**Comment by batbattur** [comment]
@djmetzle How do we deploy this? Do we just merge it?

**Comment by djmetzle** [comment]
@batbattur 
> @djmetzle How do we deploy this? Do we just merge it?

Not sure! I didn't see the repo. Is this a WP plugin? Composer module?

I suspect we'll need to release and integrate whatever module/package this is.

**Comment by batbattur** [comment]
> Not sure! I didn't see the repo. Is this a WP plugin? Composer module?

I think this is a plugin. Maybe let's confirm with @ajitbohra

**Comment by ajitbohra** [comment]
This plugin is consumed by `valkyrie` via composer 

deploying https://github.com/iFixit/valkyrie/pull/508 will enable this.

Have set the version to `dev-master` so we can skip versioning and tagging.

**Comment by ajitbohra** [comment]
@batbattur 

**For deployment order would be:**
1. This PR is merged  
2. PR on valkyrie iFixit/valkyrie#508 is merged and deployed

**Comment by batbattur** [comment]
> @batbattur
> 
> **For deployment order would be:**
> 
> 1. This PR is merged
> 2. PR on valkyrie [Fix translation strings for controllers valkyrie#508](https://github.com/iFixit/valkyrie/pull/508) is merged and deployed

Sounds good!

I don’t have write access for this repo. @djmetzle can you please merge this PR?

**Pull request merged**
